[package]
name = "libp2p-gossipsub"
description = "Gossipsub for libp2p."
version = "0.2.2"
authors = ["James Ray <16969914+jamesray1@users.noreply.github.com>"]
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking", "pubsub", "gossipsub"]
categories = ["network-programming", "asynchronous"]

[dependencies]
bs58 = "0.2.0"
bytes = "0.4"
chrono = "0.4"
cuckoofilter = "0.3.2"
custom_error = "1.3.0"
fnv = "1.0"
futures = "0.1"
libp2p-core = { path = "../../core" }
libp2p-floodsub = { path = "../floodsub" }
protobuf = "2.0.2"
rand = "0.6"
smallvec = "0.6.5"
tokio-codec = "0.1"
tokio-io = "0.1"
unsigned-varint = { version = "0.2.1", features = ["codec"] }
