[package]
name = "gossipsub"
version = "0.1.0"
authors = ["James Ray <16969914+jamesray1@users.noreply.github.com>"]
license = "Unlicense"

[dependencies]
fnv = "1.0"
futures = "0.1"
libp2p-core = { path = "../../core" }
libp2p-floodsub = { path = "../floodsub" }
log = "0.4.1"
multiaddr = { path = "../../misc/multiaddr" }
parking_lot = "0.6"
protobuf = "2.0.4"